# Generated by Django 6.0 on 2026-09-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_main', '0007_remove_notification_payload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food_count',
        ),
    ]
